#!/usr/bin/env bash

set -eo pipefail; [[ $DOKKU_TRACE ]] && set -x
APP="$1"; IMAGE="dokku/$APP"
echo "-----> Installing chromium ..."
COMMAND=$(cat <<EOF

cd /tmp && wget http://http.us.debian.org/debian/pool/main/c/chromium/chromium_125.0.6422.141-1_amd64.deb

apt install -f /tmp/chromium_125.0.6422.141-1_amd64.deb

rm /tmp/chromium_125.0.6422.141-1_amd64.deb

echo "-----> chromium installed!"
sleep 1 # wait so that docker run has not exited before docker attach
EOF
)
id=$(docker run -d $IMAGE /bin/bash -e -c "$COMMAND")
#enable logs
docker attach $id
test $(docker wait $id) -eq 0
docker commit $id $IMAGE > /dev/null
